### ISSUE TITLE
When computer reset , the power is loop.

### ISSUE THREAD

**Issue by 44886** [FlyBirdF/GIGABYTE-GAMING-X-z390#1]
z390 gaming x
i7-800
rx-560

I use your EFI ,  when I enter the macOS,that OK!

But , when I shutdown ,and next want to turn on the camputer , the power is always loop.
I must remove the battery on the motherBoard, it can turn on.

**Comment by FlyBirdF** [comment]
Please let me know your bios setting

**Comment by 44886** [comment]
I know it , when I change the Power Supply， that's ok ！
